---
title: "Moulatlet Data"
author: "Grant Foster"
date: "2024-05-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
options(java.parameters = "-Xmx20g") #Java Heap Space Limits for Maxent
library(raster)
library(tidyverse)
library(terra)
library(tidyterra)
library(ENMTML)
library(rgbif)
library(udunits2)
library(units)
library(sf)
library(stars)
library(rworldmap)
library(CoordinateCleaner)
library(dismo)
library(kernlab)
library(mgcv)
library(spatialEco)
library(dplyr)
library(rgbif)
library(rnaturalearth)
library(rJava)

sf_use_s2(FALSE) #Don't assume a sphericical geometry-therefore dist for buffer will be in units of degree
crul::set_opts(http_version = 2) #For getting gbif queries to work: https://github.com/ropensci/crul/issues/174#issuecomment-1600273273
```


Let's explore the data from this paper: https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/1365-2656.13986. 308 networks of avian-plant interactions. Maybe good? 

```{r}
Moulatlet <- read.csv(file="../Data/datalong_v08_06_2023_CLEANED.csv")
Moulatletval <- Moulatlet %>% dplyr::select(., Scientific, plant_id, interaction, lat, lon) %>% dplyr::filter(interaction %in% (c(0,1))) %>% dplyr::select(., Scientific, plant_id, interaction, lat, lon) %>% dplyr::rename(., Latitude=lat, Longitude=lon, Frugivore_Species=Scientific, Plant_Species=plant_id) %>%
  unique()

Moulatletval$interaction <- as.numeric(Moulatletval$interaction)

counts <- Moulatletval %>% dplyr::mutate(., speciesPair=paste(Frugivore_Species, Plant_Species, sep="-")) %>%
  group_by(., speciesPair) %>%
  dplyr::summarise(., pos=sum(interaction), tot=n(), neg=tot-pos)


counts <- Moulatletval %>% dplyr::mutate(., speciesPair=paste(Frugivore_Species, Plant_Species, sep="-")) %>% dplyr::select(., speciesPair ) %>% left_join(counts, .) %>% unique()
                            

counts$prop <- counts$pos/counts$tot  


#pdf(file="Figures/MoulatletInterSummary.pdf")
counts %>% dplyr::filter(., tot>9) %>%
ggplot(., aes(x=tot, y=prop))+geom_point(position = "jitter")+theme_classic()+ylab("Proportion of Interactions given Coocurence")+xlab("Number of Coocurrences")+ annotate("text", x = 31, y = .25, label = "211 interactions total")+ annotate("text", x = 31, y = .2, label = "44 birds, 37 plants")
#dev.off()


usable <- counts %>% dplyr::filter(., tot>4) %>% unique()#Number of interactions with at least 10 records
table(usable$ID)


Moulatletval <- Moulatletval %>% dplyr::mutate(., speciesPair=paste(Frugivore_Species, Plant_Species, sep="-"))

usable <- left_join(usable, Moulatletval, by="speciesPair") %>% unique()

length(unique(usable$Frugivore_Species))
length(unique(usable$Plant_Species))

library(rnaturalearth)
library(rnaturalearthdata)

world <- ne_countries(scale = "medium", returnclass = "sf")
usable$Latitude <- as.numeric(usable$Latitude)
usable$Longitude <- as.numeric(usable$Longitude)


#pdf(file="Figures/MoulatletMap_10occ.pdf", width=11, height=8.5)

#pdf(file="Figures/spatialextent.pdf")
ggplot(data = world) +
    geom_sf()+theme_classic()+ usable %>% group_by(., speciesPair) %>% slice_sample(n=1) %>%
  geom_point(data=., aes(x=Longitude, y=Latitude, col=prop), size=1.25)+scale_color_gradient(low = "firebrick", high="dodgerblue")
dev.off()

length(unique(usable$speciesPair))
```

From WOL
```{r}

amPol2 <- amPol %>% dplyr::select(., species1, species2, interaction, latitude, longitude) %>% unique()
expand(amPol, species1, species2)
amPol2$interact <- paste(amPol2$species1, amPol2$species2, sep="-")

temp <- expand(amPol, species1, species2)
temp$interact <- paste(temp$species1, temp$species2, sep="-")

temp <- amPol2 %>% select(., species1, latitude, longitude) %>% unique() %>% group_by(species1) %>% summarise(nsites_a1=length(unique(latitude))) %>% left_join(temp, ., by="species1")

temp <- amPol2 %>% select(., interact, latitude, longitude) %>% unique() %>% group_by(interact) %>% summarise(nsites_interact=length(unique(latitude))) %>% left_join(temp, ., by="interact")

table(is.na(temp$nsites_interact))

temp2 <- dplyr::filter(temp, nsites_interact>4)


temp2 <-dplyr::filter(temp2, grepl("M_PL", species2)==F) #Remove non-IDed species.



```




 Let's add predictors to our values here. 
```{r}

#Match colnames
Moulatlet <- Moulatlet %>% dplyr::rename(., Frugivore_Species=Scientific, Plant_Species=plant_id, Latitude=lat, Longitude=lon)

#
inter <- Moulatlet %>% dplyr::mutate(., speciesPair=paste(Frugivore_Species, Plant_Species, sep="-"))
inter <- dplyr::filter(inter, speciesPair%in% unique(usable$speciesPair))
inter$Latitude <- as.numeric(inter$Latitude)
inter$Longitude <- as.numeric(inter$Longitude)

#Why is there a many to 1 relationship here?
usable <- inter %>% dplyr::select(Latitude, Longitude, nplants, nbirds) %>% unique() %>% left_join(usable, ., by=c("Latitude", "Longitude"))

usable$nplants <- as.numeric(usable$nplants)
usable$nbirds <- as.numeric(usable$nbirds)
usable <- dplyr::filter(usable, is.na(nbirds)==F)
usable$type <- "Frugivory"
```




Welp, let's make SDMS of these.
```{r}
gbifQuery <- function(name, doplot=FALSE){
  record <- rgbif::occ_search(scientificName = name, hasGeospatialIssue=FALSE)
  keynum <- rgbif::name_backbone(name)$usageKey
  gbif_download <- occ_download(pred("taxonKey", keynum),format = "SIMPLE_CSV", user="riverman12", pwd="1Chicken!!!", email="fostergt@email.sc.edu")
  
  
  occ_download_wait(gbif_download)
  spdat <- occ_download_get(gbif_download) %>%
    occ_download_import() # download data

  
  world <- rnaturalearth::ne_countries(scale = "medium", returnclass = "sf")
  #ggplot(data = world) +
      #geom_sf()+geom_point(data=spdat, aes(x=decimalLongitude, y=decimalLatitude))+theme_classic()
  
  if(doplot==TRUE){
 world <- rnaturalearth::ne_countries(scale = "medium", returnclass = "sf")
  ggplot(data = world) +
      geom_sf()+geom_point(data=p1, aes(x=decimalLongitude, y=decimalLatitude))+theme_classic()
  }
  spatsmall <- dplyr::select(spdat, species, decimalLongitude, decimalLatitude)
  spatsmall <- as.data.frame(spatsmall)
  return(spatsmall)
}
```



```{r}
x <- read.csv(file="data/GBIF/occs/crataegus_monogyna.csv")

full_frugs <- list.files(path="data/occ_Dat/CentralRange_occs/") #List all files
full_frugs <- full_frugs[full_frugs!="shortened"] #remove directory
short_frugs <- list.files(path="data/occ_Dat/CentralRange_occs/shortened")

full_poll <- list.files(path="data/occ_Dat/InterMod_occs/")
full_poll <- full_poll[full_poll!="shortened"] #remove directory
short_poll <- list.files(path="data/occ_Dat/InterMod_occs/shortened")

output <- NULL
for(i in 1:length(full_frugs)){
  temp <- try(read.csv(file=paste("data/occ_Dat/CentralRange_occs/", full_frugs[i], sep="")))
  if(class(temp)=="try-error"){
    next
  }
  if(nrow(temp)==0){
    next
  }
  temp$i <- i
  temp$group <- "full_frug"
  temp$file <- full_frugs[i]
 output <- rbind(output, temp)
 
 if(i %%10 ==0){
   print(paste("done with", i, "fullfrug"))
 }
}

for(i in 1:length(short_frugs)){
  temp <- try(read.csv(file=paste("data/occ_Dat/CentralRange_occs/shortened/", short_frugs[i], sep="")))
  if(class(temp)=="try-error"){
    next
  }
    if(nrow(temp)==0){
    next
  }
  temp$i <- i
  temp$group <- "short_frug"
  temp$file <- short_frugs[i]
 output <- rbind(output, temp)
  if(i %%10 ==0)
   print(paste("done with", i, "short_frug"))
}

for(i in 1:length(full_poll)){
  temp <- try(read.csv(file=paste("data/occ_Dat/InterMod_occs/", full_poll[i], sep="")))
  if(class(temp)=="try-error"){
    next
  }
    if(nrow(temp)==0){
    next
  }
  
  temp$i <- i
  temp$group <- "full_poll"
  temp$file <- full_poll[i]
 output <- rbind(output, temp)
   if(i %%10 ==0)
   print(paste("done with", i, "full_poll"))
}

for(i in 1:length(short_poll)){
  temp <- try(read.csv(file=paste("data/occ_Dat/InterMod_occs/shortened/", short_poll[i], sep="")))
  if(class(temp)=="try-error"){
    next
  }
  if(nrow(temp)==0){
    next
  }
  temp$i <- i
  temp$group <- "short_poll"
  temp$file <- short_poll[i]
 output <- rbind(output, temp)
  output <- rbind(output, temp)
   if(i %%10 ==0)
   print(paste("done with", i, "short_poll"))
}

write.csv(output, file="data/composite_occs.csv", row.names = F)
```

```{r}
output <- read.csv(file="data/composite_occs.csv")
```


```{r}
queried <- c(short_poll, full_frugs, full_poll, short_frugs)# %>% gsub(".csv", "",.) %>% gsub("_"," ", . )
#table(queried %in% tolower(splist))
length(queried)
length(unique(output$file))
```

```{r}
toquery <- queried[(queried %in% present$Var2)==F]
```


```{r}
comb <- data.frame(table(output$file, output$species)) %>% dplyr::filter(., Freq>0)

head(comb)
table(table(output$file, output$species))
```


Remove queries that didn't work at first. 
```{r}
output <- dplyr::filter(output, file %in% queried)
```

```{r}
x <- data.frame(table(output$species, output$file))
```


```{r}
z <- read.csv(file=paste("data/occ_Dat/CentralRange_occs/", x[1], sep=""))

spnames <- unique(c(usable$Plant_Species, usable$Frugivore_Species))
comp_occs <- NULL

iters <- 35
colnames(output)
output$cells <- terra::cellFromXY(Clima, output[,5:4])
table(is.na(output$cells))
#empty <- dplyr::filter(output, is.na(cells)==TRUE) %>% dplyr::select(.,  species, decimalLatitude, decimalLongitude) %>% unique() #only 2-nice

output <- dplyr::select(output, -decimalLatitude, -decimalLongitude, -scientificName) %>% unique()
splist <- unique(output$species)
table(tolower(splist) %in% queried)

output <- cbind(output, xyFromCell(Clima, output$cells))
```

```{r}
colnames(output)
output2 <- dplyr::select(output, -genus, -scientificName, -i) %>% unique()
output <- output2
```


START HERE
```{r, eval=FALSE}
psuedos <- NULL
splist <- unique(output$file)
for(i in 1:length(splist)){
  temp <- dplyr::filter(output, file==splist[i])
  if(nrow(temp)>10000){ #If too many points, sample down to 10k
    temp <- temp[sample(1:nrow(temp), 10000, replace=F),]
  }

  #creating a 200km2 buffer to select the pseudo-absence points
    OccSf <- sf::st_as_sf(x=temp[,8:9], coords = c("x",'y'), 
                        crs=sp::CRS("EPSG:4326")) #crs=sp::CRS("+proj=longlat +ellps=WGS84
    
    OccBuffer <-sf::st_buffer(OccSf, dist=2) #Create buffer objects
    OccBuffer <-sf::st_union(OccBuffer) #Merge buffer objects into one
  
    OccBuffer <-sf::st_buffer(OccSf, dist=2) #Create buffer objects
    OccBuffer <-sf::st_union(OccBuffer) #Merge buffer objects into one
    #plot(OccBuffer)

    ##Masking the buffer so that it does not occur in the ocean
    OccBuffer2 <-as(OccBuffer, 'Spatial')
    #terra::plot(OccBuffer2)
    OccBuffer2 <- terra::vect(OccBuffer)
    OccBufferRas <-terra::rasterize(x = OccBuffer2, y=Clima)
    OccBufferRas<-raster::mask(x = OccBufferRas, mask = Clima[[1]])
    #plot(OccBufferRas)
    
    ##Selecting the pseudo absences. Since I'm doing 1:1 Presence:Psuedoabsence, I'm saving the cell number in the df as a seperate column. 
    AllPseudo <- terra::as.points(OccBufferRas)
    AllPseudo <- raster::extract(x= Clima[[1]], AllPseudo,cell=T)
    AllPseudo <-AllPseudo[-(which(AllPseudo$cell %in% temp$cells)),]
    
    temp$psuedocell <- sample(AllPseudo$cell, size=nrow(temp), replace=F)
    psuedos <- rbind(psuedos, temp)
}



output$file
for(i in 1:length(splist)){
    occ <- temp %>% dplyr::select(., decimalLongitude, decimalLatitude, species) %>% dplyr::filter(., is.na(decimalLongitude)==FALSE) %>% unique()

    occ['cells'] <-terra::cellFromXY(object= Clima[[1]], xy = occ[,1:2]) #Grab the occurance cells & remove redundant records
    sf_use_s2(FALSE) #Don't assume a spherical geometry-therefore dist for buffer will be in units of degree
  
    #creating a 200km2 buffer to select the pseudo-absence points
    OccSf <-sf::st_as_sf(x=occ[,1:2], coords = c("decimalLongitude",'decimalLatitude'), 
                        crs=sp::CRS("EPSG:4326")) #crs=sp::CRS("+proj=longlat +ellps=WGS84
  
    OccBuffer <-sf::st_buffer(OccSf, dist=2) #Create buffer objects
    OccBuffer <-sf::st_union(OccBuffer) #Merge buffer objects into one
    #plot(OccBuffer)

    ##Masking the buffer so that it does not occur in the ocean
    OccBuffer2 <-as(OccBuffer, 'Spatial')
    #terra::plot(OccBuffer2)
    OccBuffer2 <- terra::vect(OccBuffer)
    OccBufferRas <-terra::rasterize(x = OccBuffer2, y=Clima)
    OccBufferRas<-raster::mask(x = OccBufferRas, mask = Clima[[1]])
    #plot(OccBufferRas)
    
    ##Selecting the pseudo absences. Since I'm doing 1:1 Presence:Psuedoabsence, I'm saving the cell number in the df as a seperate column. 
    AllPseudo <- terra::as.points(OccBufferRas)
    AllPseudo <- raster::extract(x= Clima[[1]], AllPseudo,cell=T)
    AllPseudo<-AllPseudo[-(which(AllPseudo$cell %in% occ$cells)),]
    occ$psuedocell <- sample(AllPseudo$cell, size=nrow(occ), replace=F)
    
    comp_occs <- rbind(comp_occs, occ) #rbind lates species to composite df
    if(i%%10==0){ #if it's an interval of 10 save just in case
      write.csv(comp_occs, file="data/comp_occurances.csv", row.names = F)
    }
    if(i==iters){ #if it's the full number of spp, then do save the final file. 
      write.csv(comp_occs, file="data/comp_occurances.csv", row.names = F)
    }
    print(i)
}
```



Getting data
```{r}
#Getting climate data
Clima <- geodata::worldclim_global("worldclim", var="bio", res=2.5)
#terra::plot(Clima[[1]])

#Here's loading all of these in and merging them
#tile53 <- raster::stack("worldclim/wc2.1_tiles/tile_53_wc2.1_30s_bio.tif")
#tile52 <- raster::stack("worldclim/wc2.1_tiles/tile_52_wc2.1_30s_bio.tif")
#tile29 <- raster::stack("worldclim/wc2.1_tiles/tile_29_wc2.1_30s_bio.tif")
#tile28 <- raster::stack("worldclim/wc2.1_tiles/tile_28_wc2.1_30s_bio.tif")
#tile41 <- raster::stack("worldclim/wc2.1_tiles/tile_41_wc2.1_30s_bio.tif")
#tile40 <- raster::stack("worldclim/wc2.1_tiles/tile_40_wc2.1_30s_bio.tif")

#SA <- terra::merge(tile53, tile52, tile29, tile28, tile41, tile40)
#plot(SA)
Climastack <- raster::stack(Clima)
```






Performing PCA - Don't Run-This crashes computers!!!
```{r}
datas <- read.csv(file="data/psuedos.csv")[,-1]

datas$PA <- 1 #Add a 1 to the presence absence file-my b, changed my mind how I wanted things organized

abs <- dplyr::select(datas, -cells) %>% dplyr::mutate(., decimalLongitude=NA, decimalLatitude=NA, PA=0) %>% dplyr::rename(., cells=psudeocells)
pres <- dplyr::select(datas, -psudeocells) #Create a new empty cell for psuedooccurances

comp_long <- rbind(abs, pres)
rm(abs, pres)
```

```{r}
#c(comp_occs$cells, comp_occs$cells)
ext <- terra::extract(Climastack, comp_long$cells)

comp_long$na_pres <- is.na(ext[,1]) #Add

#Running a PCA over our climatic data
#EnvCoord<-na.omit(raster::rasterToPoints(Climastack)) #Make raster into long df of points
#PcaR<-EnvCoord[,-c(1:2)] #remove latlong for PCA

#Scale transform 
DScale <- data.frame(apply(na.omit(ext),2,scale)) %>% na.omit()#scale
#Run the  PCA 
DPca <- prcomp(DScale,retx=TRUE,center=F,scale=F) #run PCA on scaled data

#% of the variation explained
NEixos<-length(summary(DPca)$importance[3,])
CumVar<-summary(DPca)$importance[3,]
VarEx<-data.frame(CumVar)

#Getting the loadings and transforming it into a dataframe
Eix<-as.data.frame(DPca$x) #Grab the PCA loadings

EixXY <- comp_long %>% dplyr::filter(., na_pres==FALSE) %>% cbind(., Eix) 
EixXY <- terra::xyFromCell(Clima,EixXY$cells) %>% cbind(., EixXY)

spob <- EixXY %>% dplyr::select(., -decimalLongitude, -decimalLatitude, -species, -cells, -PA, -na_pres) %>% unique()

#EixXY<-cbind(ext[,(1:2)],Eix) #re add back in the coordinates from earlier
sp::gridded(spob)<- ~x+y #Create large spatial pixels df (prep to reconvert to raster)
PCAPr <-raster::stack(spob) #create a rasterstack for each 
raster.comb<-PCAPr[[6:(sum(VarEx<=0.95)+6)]] #only include the axis necessary to explain 95% of variation
class(raster.comb)
```






Given our records, here are our Maxent Models

```{r, eval=TRUE}

for(i in 295:length(splist)){
    Occ <- comp_long[comp_long$file==splist[i],] #Filter to target species
    if(nrow(Occ)<20){
      next #Skip if there are no records
    }
    
    xy <- terra::xyFromCell(Clima, Occ$cells) %>% as.data.frame() %>% dplyr::rename(., "Long"=x, "Lat"=y) 
    
    Occurrences <- cbind(Occ, xy)#, Aspots)
    id.training <-sample(1:(nrow(Occurrences)/2),round(0.75*nrow(Occurrences)/2,0)) 
    pres <- dplyr::filter(Occurrences, PA==1)
    abs <- dplyr::filter(Occurrences, PA==0)
  
    training <-dismo::prepareData(x=raster.comb, p=pres[id.training,c("Long", "Lat")], b=abs[id.training,c("Long", "Lat")]) 
    testing<-dismo::prepareData(x=raster.comb, p=pres[-id.training,c("Long", "Lat")], b=abs[-id.training,c("Long", "Lat")])    
    training<-na.omit(training)
    testing<-na.omit(testing)
      
    Occurrences2<-Occurrences
    #colnames(Occurrences2)<-rep(c('Long','Lat'),2)
    #testingPresPA<-rbind.data.frame(Occurrences2[-id.training,1:2],Occurrences2[-id.training,3:4])
    
      ##Maxent
    Sys.setenv(NOAWT=TRUE)
    Maxent.Model <- dismo::maxent(x = as.data.frame(training[,-1]), p = as.data.frame(training[,1])) #Train Maxent Model
    
    #Maxent.0  <-dismo::predict(object = Maxent.Model, x = raster.comb, args='outputformat=cloglog') 
    
    Maxent.eval<-dismo::evaluate(p = testing[testing[,"pb"]==1,-1], a = testing[testing[,"pb"]==0,-1], model = Maxent.Model)

    save(Maxent.Model, Maxent.eval, file=paste("MaxentModels2/Maxent_test_", gsub(pattern=" ", gsub(".csv", "", splist[i]), replacement="_"), ".Rda", sep=""))
    rm(Maxent.Model, Maxent.eval)
    print(i)
}    

Maxent.0  <-dismo::predict(object = Maxent.Model, x = raster.comb, args='outputformat=cloglog') #Predict suitability according to trained model
plot(Maxent.0)

```

Plant-Pollinator Interactions
```{r}
Maxent.eval
Maxent.Model$prediction
```


